#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Feb 19 11:40:39 EST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.4b.zip
enableShaders=true
